# Generated by Django 3.0 on 2020-05-16 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediacenter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='file_path',
            field=models.ImageField(upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='file_path',
            field=models.FileField(upload_to='video/'),
        ),
    ]
