# Generated by Django 3.0 on 2020-05-17 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channels_presence', '0001_initial'),
        ('mediacenter', '0002_auto_20200516_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_type', models.CharField(choices=[('Video', 'Video'), ('Photo', 'Photo')], default='Video', max_length=5)),
                ('photos', models.ManyToManyField(related_name='photos', to='mediacenter.Photo')),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='channels_presence.Room')),
                ('videos', models.ManyToManyField(related_name='videos', to='mediacenter.Video')),
            ],
        ),
    ]
