# Generated by Django 3.0 on 2020-05-17 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels_presence', '0001_initial'),
        ('mediacenter', '0003_roomsettings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoomSettings',
            new_name='RoomSetting',
        ),
    ]
