# Generated by Django 3.0 on 2020-05-17 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediacenter', '0004_auto_20200517_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomsetting',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='photos', to='mediacenter.Photo'),
        ),
        migrations.AlterField(
            model_name='roomsetting',
            name='videos',
            field=models.ManyToManyField(blank=True, related_name='videos', to='mediacenter.Video'),
        ),
    ]
