# Generated by Django 3.0 on 2020-05-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediacenter', '0006_auto_20200518_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomsetting',
            name='room_name',
            field=models.CharField(blank=True, max_length=144),
        ),
    ]
